export const TERRAIN_SYMBOLS = {
  water: 'water',
  ocean: 'ocean',
  lake: 'lake',
  river: 'river',
  stream: 'stream',
  pond: 'pond',
  marsh: 'marsh',
  swamp: 'swamp',
  bog: 'bog',
  fen: 'fen',
  mangrove: 'mangrove',
  estuary: 'estuary',
  delta: 'delta',
  mangrove_forest: 'mangrove_forest',
  kelp_forest: 'kelp_forest',
  coral_reef: 'coral_reef',
  polar_sea: 'polar_sea',
  open_ocean: 'open_ocean',
  abyssal_deep: 'abyssal_deep',
  seamount: 'seamount',
  open: 'open',
  grassland: 'grassland',
  plains: 'plains',
  savanna: 'savanna',
  tundra: 'tundra',
  taiga: 'taiga',
  desert: 'desert',
  sand: 'sand',
  wetland: 'wetland',
  coast: 'coast',
  temperate: 'temperate',
  tropical: 'tropical',
  rainforest: 'rainforest',
  jungle: 'jungle',
  alpine: 'alpine',
  island: 'island',
  mountain: 'mountain',
  volcanic: 'volcanic',
  forest: 'forest',
  ore: 'ore',
  stone: 'stone'
};

export default TERRAIN_SYMBOLS;
